/*
  Buzzer
    @omzn  2020/10/20
*/

#include <stdbool.h>
#include <stdint.h>
#include <math.h>
#include "inc/hw_i2c.h"
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "inc/hw_types.h"
#include "inc/hw_qei.h"
#include "inc/hw_timer.h"
#include "driverlib/rom.h"
#include "driverlib/gpio.h"
#include "driverlib/i2c.h"
#include "driverlib/systick.h"
#include "driverlib/interrupt.h"
#include "driverlib/pin_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/uart.h"
#include "driverlib/pwm.h"
#include "driverlib/timer.h"

#include "driverlib/qei.h"
#include "utils/uartstdio.h"
#include "utils/uartstdio.c" //strong-arm method

#include "periphConf.h" //generated by PinMux

#include "my_util.h"

#include "buzzer.h"

//*****************************************************************************
// Global variables
//*****************************************************************************

//*****************************************************************************
//
// This function sets up UART0 to be used for a console to display information
// as the example is running.
//
//*****************************************************************************


void initConsole(void) {
    // Enable GPIO port A which is used for UART0 pins.
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
    // Configure the pin muxing for UART0 functions on port A0 and A1.
    // This step is not necessary if your part does not support pin muxing.
    GPIOPinConfigure(GPIO_PA0_U0RX);
    GPIOPinConfigure(GPIO_PA1_U0TX);
    // Enable UART0 so that we can configure the clock.
    SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);
    // Use the internal 16MHz oscillator as the UART clock source.
    UARTClockSourceSet(UART0_BASE, UART_CLOCK_PIOSC);
    // Select the alternate (UART) function for these pins.
    GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);
    // Initialize the UART for console I/O.
    UARTStdioConfig(0, 9600, 16000000);
}

void initInterruptPins(void) {
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
    GPIODirModeSet(GPIO_PORTF_BASE, INT_ALL_BUTTONS, GPIO_DIR_MODE_IN);
    GPIOPadConfigSet(GPIO_PORTF_BASE, INT_ALL_BUTTONS,
                     GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);
    GPIOIntClear(GPIO_PORTF_BASE,INT_ALL_BUTTONS);


    UARTprintf("Inter\n");
}

//*****************************************************************************
// Event handers
//*****************************************************************************

void SysTickIntHandler(void) {
    static uint32_t led_color = LED_ALL;
    static uint32_t tick_count = 0;
    if (tick_count % 16 == 0) {
        led_color = ~led_color;
        tick_count = 0;
        /*
         * Note that the 2nd param of GPIOPinWrite denotes pins to be written in bit pattern.
         * The 3rd param of denotes values to be written in bit pattern.
         * What really written to GPIO pins is a logical AND of 2nd and 3rd params.
         */
        GPIOPinWrite(GPIO_PORTF_BASE,LED_RED,led_color);
    }
    tick_count++;
}

void SW1PinIntHandler(void) {
    static bool buzzer_on = false;
    static uint32_t now_voice = O4G;

    GPIOIntDisable(GPIO_PORTF_BASE,INT_ALL_BUTTONS);
    GPIOIntClear(GPIO_PORTF_BASE,INT_ALL_BUTTONS);
    UARTprintf("Now voice: %d\n",now_voice);
    if(!buzzer_on){
        switch(now_voice){
            case O4C:
                now_voice = O4D;
                break;
            case O4D:
                now_voice = O4E;
                break;
            case O4E:
                now_voice = O4F;
                break;
            case O4F:
                now_voice = O4G;
                break;
            case O4G:
                now_voice = O4C;
                break;
        }

        toneBuzzer(now_voice);
    }else{
        restBuzzer();
    }
    buzzer_on = !buzzer_on;
    GPIOIntEnable(GPIO_PORTF_BASE,INT_ALL_BUTTONS);
}

int main(void) {
    // Set the clocking to run directly from the crystal.
    ROM_SysCtlClockSet(SYSCTL_SYSDIV_1 | SYSCTL_USE_OSC | SYSCTL_OSC_MAIN |
                       SYSCTL_XTAL_16MHZ);

    // Initialize console
    initConsole();
    UARTprintf("Buzzer!\n");

    // Set up ports hardware (see periphConf.c)
    PortFunctionInit();

    // Set up interrupts (you can specify GPIO interrupt initialization here)
    initInterruptPins();

    // Initialize buzzer
    initBuzzer();

    // toneBuzzer(O4C);
    PWMGenPeriodSet(PWM0_BASE, PWM_GEN_1, O4C);
    PWMPulseWidthSet(PWM0_BASE, PWM_OUT_3, O4C/2);

    GPIOIntRegister(GPIO_PORTF_BASE,SW1PinIntHandler);
    GPIOIntEnable(GPIO_PORTF_BASE,INT_ALL_BUTTONS);

    SysTickPeriodSet(SysCtlClockGet() / SYSTICKS_PER_SEC);
    SysTickEnable();
    SysTickIntRegister(SysTickIntHandler);
    SysTickIntEnable();

    while(1);
}
